### ISSUE TITLE
sync also "my music" => "albums"

### ISSUE THREAD

**Issue by danipindado** [aartek/trikatuka2#2]
hi, 
congratulations for the great app. 
it would be great that also albums" section is synced between accounts. 
as of now, only "playlists" and "songs" are synced. 
most of the time I add whole albums to my account.  after using your tool, the "albums" section of the 2nd account is empty. it would be great if talso albums would be synced. 

keep the good work!
![2017-06-03_17h06_16](https://cloud.githubusercontent.com/assets/22555491/26754693/8cdb48d0-487f-11e7-8454-b04e5f4b2853.png)

**Comment by aartek** [comment]
Thanks for your feedback! Unfortunately, currently I have no time to make improvements in this app :(
If you want and if you know how to add this functionalitu, you can make a pull request! :)

**Comment by aartek** [comment]
Currently it's possible to also transfer the albums
