### ISSUE TITLE
Running but i can't access it

### ISSUE THREAD

**Issue by WillyRL** [aartek/trikatuka2#3]
Hi there, i got this script running, but can't access it, just loading
root@nodejs-s-1vcpu-1gb-sgp1-01:~/trikatuka2# node server.js
Magic happens on port 8080

where does the access log and error log or any log stored?

**Comment by aartek** [comment]
Hi, the readme miss one important thing. When running locally you need to set one more environmental variable - `name=dev`. I have to change it, and describe it better.

So:
```
export name=dev
export CLIENT_ID=xxxxxx
export CLIENT_SECRET=xxxxxx
npm start
```
and app should work under the http://localhost:7878.

You also need to register the following urls as the valid redirect uris in the spotify client settings:
- `http://localhost:7878/client_auth_callback` 
- `http://localhost:7878/user_auth_callback`

**Comment by aartek** [comment]
You may need to change lines 36-39 in the `server.js` file.
```
server_port = process.env.TRIKATUKA_PORT || 8080;
server_ip_address = '0.0.0.0';
baseUrl = 'http://www.trikatuka.aknakn.eu';
 ```
`baseUrl` is the key to make the authentication work - it's used in the spotify oauth requests as the redirect uri. You need to set your digital ocean url or ip here. (It should be also settable by the env variable - I will fix it). If you need to run your app on any other port than 8080, please also set the `TRIKATUKA_PORT` env variable.

When you change the above settings you won't need to set the `name=dev` env which I mentioned in my previous answer.

**Comment by WillyRL** [comment]
Hi There,

Its working and running, Thank you very much :D

**Comment by WillyRL** [comment]
Now i have problem with the Callback when try to sign in
already add the callbacks url

do.willyrl.com/user_auth_callback
and do.willyrl.com/client_auth_callback

**Comment by aartek** [comment]
I got "INVALID_CLIENT: Invalid redirect URI" when trying to singin on your website. Are you sure you defined the callback uris in the right spotify client settings? They must be defined in the same project from which you use the clientId and clientSecret.
 
Redirect URIs for my app:
- http://trikatuka.aknakn.eu/user_auth_callback
- http://trikatuka.aknakn.eu/client_auth_callback
- http://www.trikatuka.aknakn.eu/client_auth_callback
- http://www.trikatuka.aknakn.eu/user_auth_callback

Remember to have the "http://" prefix defined in the redirect uris.

**Comment by WillyRL** [comment]
![image](https://user-images.githubusercontent.com/11781111/44361531-5cbc1c80-a4e8-11e8-91fd-c05112582bdb.png)
Hi There, 

I have changed my domain to playlist.sepotifai.xyz , and have changed the callback url 
Should i wait for a moment to have the Spotify system recognize my domain ?

Thank you.

**Comment by aartek** [comment]
I did a quick check and you have ":80" in sent redirect_uri query parameter, so it doesn't match the above list. 

This is my script to start the app on aws

```
#!/bin/sh

export CLIENT_ID=xxx
export CLIENT_SECRET=xxx
export TRIKATUKA_PORT=8083

cd trikatuka2
npm run build
node server.js
```

And in the `server.js` I have:
```
if (process.env.name === 'dev') {
    server_port = 7878;
    server_ip_address = 'localhost';
    baseUrl = 'http://localhost:7878'
}
else {
    server_port = process.env.TRIKATUKA_PORT || 8080;
    server_ip_address = '0.0.0.0';
    baseUrl = 'http://www.trikatuka.aknakn.eu';
}
```

**Comment by WillyRL** [comment]
Hi,

Its working !! 

Thank you very much bro
