### ISSUE TITLE
The tool did not transfer "Liked Songs" to the new account

### ISSUE THREAD

**Issue by erhanalankus** [aartek/trikatuka2#6]
Hey,

Thanks for this tool.

I just wanted you to know this is not a request for you to fix this. I want to take a look at this when I have the time :)

Creating this issue to keep track.

**Comment by aartek** [comment]
Hi, what exactly do you mean? I've just tested using "Tracks" tab and got transfered 11 faved songs from one account to another. Doesn't it work for you?

**Comment by erhanalankus** [comment]
Well, I just noticed that I didn't have the songs from my previous account in the list.
I may have removed them from the new account and forgotten about it :)

I'll now close this, later today I'll test it with the same "old account" and if it doesn't work, I'll reopen it.

Thanks for the quick response.
